language: node_js
sudo: false
git:
  depth: 10
node_js:
  - "4"
  - "6"
install:
  - git clone https://github.com/apache/cordova-js --depth 10
  - git clone https://github.com/apache/cordova-fetch --depth 10
  - git clone https://github.com/apache/cordova-serve --depth 10
  - git clone https://github.com/apache/cordova-common --depth 10
  - npm link cordova-js
  - npm link cordova-common
  - npm link cordova-serve
  - (cd cordova-fetch && npm link ../cordova-common && npm install)
  - npm link cordova-fetch
  - npm install
  # Workaround for npm/npm#10343 when dependency of linked module is moved to dependent
  # module's 'node_modules' In our case 'cordova-common' -> jshint' -> 'cli' dependency
  # is moved to 'cordova-lib' and hence 'npm run jshint' on 'cordova-common' is failing
  - "(cd cordova-common && npm install)"
  - (cd cordova-fetch && npm install && npm link ../cordova-common)

script:
  - "npm run e2e-tests"
  - "npm run ci"
