# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - git clone https://github.com/apache/cordova-js --depth 10
  - cd cordova-lib
  - npm link ../cordova-js
  - cd ../cordova-common
  - npm install
  - cd ../cordova-fetch
  - npm link ../cordova-common
  - npm install
  - cd ../cordova-lib
  - npm link ../cordova-common
  - npm link ../cordova-serve
  - npm link ../cordova-fetch
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - "cd ../cordova-common && npm test"
  - "cd ../cordova-fetch && npm test"
  - "cd ../cordova-lib && npm test"
